---
- hosts: wordpress_docker
  remote_user: blamas
  become: yes
  tasks:
    - name: "Cria e roda conteiner MySQL"
      docker_container:
        name: banco
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: P@ssw0rd
    - name: "Cria e roda container WordPress"
      docker_container:
        name: catalogo
        image: wordpress
        links:
          - "banco:mysql"
        ports:
          - "8080:80"